function OnCast()
    local owner = Context.GetOwner()
    owner.TriggerAnimation(Animation)
    owner.RotateTowards(Context.dir)
    owner.StopRotation()
    owner.SlowMovement()
    Delay(Windup)
    local projectile = CreateBasicProjectile(0, Context, Range, Speed, true)
    projectile.SetOnHit(function (target) 
        target.ApplyDamage(20, DamageType)
        local _context = CreateCastContext(Context.GetOwner(), projectile.GetPosition(), Context.dir)
        CastAbility(5, _context)
        end)
    projectile.Fire()
    owner.RestoreMovement()
end
